# Generated by Django 5.2.6 on 2025-09-29 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contraseña_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'admin'), ('alumno', 'alumno'), ('docente', 'docente')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id_progreso', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='admin_app.curso')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='admin_app.usuario')),
            ],
            options={
                'db_table': 'progreso',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'activo'), ('completado', 'completado'), ('abandonado', 'abandonado')], default='activo', max_length=10)),
                ('curso', models.ForeignKey(db_column='id_curso', on_delete=django.db.models.deletion.CASCADE, to='admin_app.curso')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='admin_app.usuario')),
            ],
            options={
                'db_table': 'inscripciones',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(db_column='docente_id', limit_choices_to={'rol': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.usuario'),
        ),
    ]
